### ISSUE TITLE
Microverse peer-to-peer code review 12/11/21

### ISSUE THREAD

**Issue by tacodtripe** [algerina/Unit-test-practice#2]
Hello, your code works almost as it should, there are just a few modifications I may suggest.

https://github.com/algerina/Unit-test-practice/blob/1e9b52e006560daff461795f97609fdcd5239d59/stringLength.js#L9

The quotes are preventing your code to be exported properly

https://github.com/algerina/Unit-test-practice/blob/1e9b52e006560daff461795f97609fdcd5239d59/capitalize.js#L5

The proper syntax to throw an error should be `throw new Error('error message')

https://github.com/algerina/Unit-test-practice/blob/1e9b52e006560daff461795f97609fdcd5239d59/calculator.js#L1

Kindly define your constructor method to expect the two numbers as parameters

https://github.com/algerina/Unit-test-practice/blob/1e9b52e006560daff461795f97609fdcd5239d59/calculator.js#L19

You may create the instance of the class before you export it.

https://github.com/algerina/Unit-test-practice/blob/1e9b52e006560daff461795f97609fdcd5239d59/calculator.test.js#L1

Kindly remove the curly braces so your const is defined

https://github.com/algerina/Unit-test-practice/blob/1e9b52e006560daff461795f97609fdcd5239d59/calculator.test.js#L19

There is a typo in the `calculator.divide` calling

That may be all from my side,
cheers and happy coding :v:

**Comment by algerina** [comment]
All the issues are fixed, thank you.
